on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cyclo
      id: cyclo
      run: |
        npm install
        npm run calc > cyclo.txt
      continue-on-error: true
    - name: Actions summary
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const cycloContent = fs.readFileSync('cyclo.txt', 'utf8');

          core.summary
            .addHeading('Summary Title')
            .addRaw('\n#### Test result', true)
            .addRaw('Passed: 100, Failed: 60', true)
            .addRaw('\n#### Lint result', true)
            .addDetails('詳細', 
              '<pre>'
              +['１行目','2行目','3行目','4行目'].join('\n')
              +'</pre>'
            )
            .addRaw('\n#### Coverage', true)
            .addRaw('95%', true)
            .addRaw('\n#### 複雑度', true)
            .addRaw('${{ steps.cyclo.outcome }}', true)
            .addDetails('詳細', '<pre>'+cycloContent+'</pre>')
            .write()
    - name: Check cyclo status
      if: steps.cyclo.outcome == 'failure'
      run: exit 1