on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: cyclo
      run: |
        npm run calc > cyclo.txt
      continue-on-error: true
    - name: Generate release notes
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const cycloContent = fs.readFileSync('cyclo.txt', 'utf8');
          core.summary
            .addHeading('Release info')
            .addRaw('\n#### Test Result', true)
            .addRaw('Passed: 100, Failed: 60', true)
            .addRaw('\n#### 静的解析結果', true)
            .addDetails('詳細', '<pre>aaaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\n</pre>')
            .addRaw('\n#### ウィルスチェック', true)
            .addRaw('OK', true)
            .write()