on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Generate release notes
      uses: actions/github-script@v7
      with:
        script: |
          core.summary
            .addHeading('Release info')
            .addRaw('### Test Result', true)
            .addRaw('Passed: 100, Failed: 60', true)
            .addRaw('### 静的解析結果', true)
            .addDetails('詳細', 'aaaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\n')
            .addRaw('### ウィルスチェック', true)
            .addRaw('OK', true)
            .write()