on:
  workflow_dispatch:
    inputs:
      previousTag:
        description: previous
        required: true
      releaseTag:
        description: The tag
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Generate release notes
      uses: actions/github-script@v7
      with:
        script: |
          const releaseTag = context.payload.inputs.releaseTag
          const previousTag = context.payload.inputs.previousTag
          
          core.summary.addHeading('Release info')
          core.summary.addRow('### Test Result')
          core.summary.addRow('Passed: 100, Failed: 60')
          core.summary.addRow('### 静的解析結果')
          core.summary.addDetail('詳細', 'aaaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\naaaaaa\nbbbbbbb\n')
          core.summary.addRow('### ウィルスチェック')
          core.summary.addRow('OK')
          core.summary.write()