on:
  push: 
  workflow_dispatch:
    inputs:
      previousTag:
        description: aaaaaaa
        required: true
      releaseTag:
        description: bbbbbb
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Generate release notes
      run: echo "test"