on:
  push:

jobs:
  # cpplint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - run: git log
  #   - run: touch created.txt
  #   - run: echo before > created.txt
  #   - run: git status
  #   - uses: actions/upload-artifact@v4
  #     with:
  #       name: before
  #       path: created.txt # or path/to/artifact
  #   - uses: actions/checkout@v4
  #     with:
  #       ref: v1.0.4
  #   - run: echo after > created.txt
  #   - uses: actions/upload-artifact@v4
  #     with:
  #       name: after
  #       path: created.txt # or path/to/artifact
  #   - run: git status
  #   - run: git log
  #   - uses: actions/download-artifact@v4
  #     with:
  #       name: before
  #       path: before
  #   - run: ls before
  #   - run: git status
  # pattern2:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #     with: 
  #       path: after
  #   - uses: actions/checkout@v4
  #     with: 
  #       ref: v1.0.4
  #       path: before
  #   - run: ls -l
  #   - run: cd before; git log
  #   - run: cd after; git log
  test:
    runs-on: ubuntu-latest
    steps:
    - run: which docker
    - run: docker --version
    - run: podman search --limit 10 postgres
    - run: docker compose up -d 
  # user:
  #   - run: echo $USER
  # pattern:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       fetch-depth: 0
  #   - run: git show
  #   - run: touch created.txt
  #   - run: git checkout v1.0.4
  #   - run: git show
  #   - run: git status
