on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: git log
    - run: touch created.txt
    - run: git status
    - uses: actions/checkout@v4
      with:
        ref: v1.0.4
    - run: git status
    - run: git log