on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "hello"
          echo "${{ github.event.payload.release }}"
      - name: Generate release notes
        uses: actions/github-script@v7
        with:
          script: |
            const summary = core.summary
            .addTable(
              [ 
                [{data: '',header: true}, {data: 'Result', header: true}],
                ['Test Result', 'OK'],
                ['Lint Result', 'NG'],
                ['Coverage Result', 'OK'],
              ]
            )
            .addRaw('\n#### Test result', true)
            .addRaw('Passed: 100, Failed: 60', true)
            .addRaw('\n#### Lint result', true)
            .addDetails('詳細', 
              '<pre>'
              +['１行目','2行目','3行目','4行目'].join('\n')
              +'</pre>'
            )
            .addRaw('\n#### Coverage', true)
            .addRaw('95%', true)
            const txt = summary.stringify()
            summary.write()

            const releaseId = context.payload.release.id
            const release = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId
            })
            const summaryUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;

            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
              body: release.data.body + "\n" + `[actions](${summaryUrl})\n\n${txt}`
            })
    #       if (previousTag) {
    #         releaseNotesParams.previous_tag_name = previousTag;
    #       }

    #       const releaseNotes = await github.rest.repos.generateReleaseNotes(releaseNotesParams);
    #       console.log(releaseNotes);

    #       await github.rest.repos.createRelease({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         tag_name: releaseTag,
    #         name: releaseTag,
    #         body: releaseNotes.data.body,
    #       });